# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src_ui/ui_add_videos.ui'
#
# Created: Mon May 23 21:42:32 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from watchvideo.qt import QtCore, QtGui

class Ui_AddVideos(object):
    def setupUi(self, AddVideos):
        AddVideos.setObjectName("AddVideos")
        AddVideos.resize(556, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/media/harddisk-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddVideos.setWindowIcon(icon)
        self.gridLayout_3 = QtGui.QGridLayout(AddVideos)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.g_pasteLinks = QtGui.QGroupBox(AddVideos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_pasteLinks.sizePolicy().hasHeightForWidth())
        self.g_pasteLinks.setSizePolicy(sizePolicy)
        self.g_pasteLinks.setObjectName("g_pasteLinks")
        self.gridLayout_2 = QtGui.QGridLayout(self.g_pasteLinks)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tedit_pasteLinks = QtGui.QTextEdit(self.g_pasteLinks)
        self.tedit_pasteLinks.setObjectName("tedit_pasteLinks")
        self.gridLayout_2.addWidget(self.tedit_pasteLinks, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.g_pasteLinks, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.b_checkLinks = QtGui.QPushButton(AddVideos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_checkLinks.sizePolicy().hasHeightForWidth())
        self.b_checkLinks.setSizePolicy(sizePolicy)
        self.b_checkLinks.setMinimumSize(QtCore.QSize(140, 81))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/media/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_checkLinks.setIcon(icon1)
        self.b_checkLinks.setAutoRepeatInterval(100)
        self.b_checkLinks.setObjectName("b_checkLinks")
        self.gridLayout.addWidget(self.b_checkLinks, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.tree_validLinks = QtGui.QTreeWidget(AddVideos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_validLinks.sizePolicy().hasHeightForWidth())
        self.tree_validLinks.setSizePolicy(sizePolicy)
        self.tree_validLinks.setMinimumSize(QtCore.QSize(0, 0))
        self.tree_validLinks.setRootIsDecorated(False)
        self.tree_validLinks.setAllColumnsShowFocus(True)
        self.tree_validLinks.setWordWrap(False)
        self.tree_validLinks.setHeaderHidden(False)
        self.tree_validLinks.setObjectName("tree_validLinks")
        self.tree_validLinks.headerItem().setText(1, "Format(s)")
        self.tree_validLinks.header().setVisible(True)
        self.tree_validLinks.header().setCascadingSectionResizes(False)
        self.tree_validLinks.header().setDefaultSectionSize(140)
        self.tree_validLinks.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tree_validLinks, 1, 0, 1, 2)
        self.label_status = QtGui.QLabel(AddVideos)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 2, 0, 1, 1)
        self.rb_playDirectly = QtGui.QRadioButton(AddVideos)
        self.rb_playDirectly.setChecked(False)
        self.rb_playDirectly.setObjectName("rb_playDirectly")
        self.gridLayout_3.addWidget(self.rb_playDirectly, 3, 0, 1, 1)
        self.rb_download = QtGui.QRadioButton(AddVideos)
        self.rb_download.setChecked(True)
        self.rb_download.setObjectName("rb_download")
        self.gridLayout_3.addWidget(self.rb_download, 4, 0, 1, 1)
        self.frame_dl = QtGui.QFrame(AddVideos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_dl.sizePolicy().hasHeightForWidth())
        self.frame_dl.setSizePolicy(sizePolicy)
        self.frame_dl.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_dl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_dl.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_dl.setObjectName("frame_dl")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_dl)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_destFolder = QtGui.QLabel(self.frame_dl)
        self.label_destFolder.setMinimumSize(QtCore.QSize(130, 25))
        self.label_destFolder.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_destFolder.setObjectName("label_destFolder")
        self.horizontalLayout_3.addWidget(self.label_destFolder)
        self.ledit_destFolder = QtGui.QLineEdit(self.frame_dl)
        self.ledit_destFolder.setMinimumSize(QtCore.QSize(0, 27))
        self.ledit_destFolder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ledit_destFolder.setReadOnly(False)
        self.ledit_destFolder.setObjectName("ledit_destFolder")
        self.horizontalLayout_3.addWidget(self.ledit_destFolder)
        self.b_folder = QtGui.QToolButton(self.frame_dl)
        self.b_folder.setMinimumSize(QtCore.QSize(33, 27))
        self.b_folder.setStatusTip("None")
        self.b_folder.setObjectName("b_folder")
        self.horizontalLayout_3.addWidget(self.b_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_afterDownload = QtGui.QLabel(self.frame_dl)
        self.label_afterDownload.setObjectName("label_afterDownload")
        self.horizontalLayout.addWidget(self.label_afterDownload)
        self.combo_options = QtGui.QComboBox(self.frame_dl)
        self.combo_options.setObjectName("combo_options")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.horizontalLayout.addWidget(self.combo_options)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.frame_dl, 5, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(AddVideos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 6, 1, 1, 1)

        self.retranslateUi(AddVideos)
        QtCore.QMetaObject.connectSlotsByName(AddVideos)

    def retranslateUi(self, AddVideos):
        AddVideos.setWindowTitle(QtGui.QApplication.translate("AddVideos", "Add Videos", None, QtGui.QApplication.UnicodeUTF8))
        self.g_pasteLinks.setTitle(QtGui.QApplication.translate("AddVideos", "Paste link(s) here:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_checkLinks.setText(QtGui.QApplication.translate("AddVideos", "Get Videos", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_validLinks.headerItem().setText(0, QtGui.QApplication.translate("AddVideos", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_playDirectly.setText(QtGui.QApplication.translate("AddVideos", "Play directly from link(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_download.setText(QtGui.QApplication.translate("AddVideos", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_destFolder.setText(QtGui.QApplication.translate("AddVideos", "Destination Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_folder.setToolTip(QtGui.QApplication.translate("AddVideos", "Choose Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.b_folder.setText(QtGui.QApplication.translate("AddVideos", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_afterDownload.setText(QtGui.QApplication.translate("AddVideos", "After Download:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(0, QtGui.QApplication.translate("AddVideos", "Do Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(1, QtGui.QApplication.translate("AddVideos", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(2, QtGui.QApplication.translate("AddVideos", "Convert to Ogg/Vorbis (audio)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(3, QtGui.QApplication.translate("AddVideos", "Convert to Ogg/Theora (video)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(4, QtGui.QApplication.translate("AddVideos", "Rip Audio", None, QtGui.QApplication.UnicodeUTF8))

from watchvideo import icons_rc
assert icons_rc
