# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src_ui/ui_preferences.ui'
#
# Created: Mon May 23 21:42:32 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from watchvideo.qt import QtCore, QtGui

class Ui_PreferencesWindow(object):
    def setupUi(self, PreferencesWindow):
        PreferencesWindow.setObjectName("PreferencesWindow")
        PreferencesWindow.resize(591, 300)
        PreferencesWindow.setMinimumSize(QtCore.QSize(591, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/media/preferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PreferencesWindow.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(PreferencesWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(PreferencesWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.t_preferences = QtGui.QWidget()
        self.t_preferences.setObjectName("t_preferences")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.t_preferences)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_builtinPlayer = QtGui.QCheckBox(self.t_preferences)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_builtinPlayer.sizePolicy().hasHeightForWidth())
        self.cb_builtinPlayer.setSizePolicy(sizePolicy)
        self.cb_builtinPlayer.setObjectName("cb_builtinPlayer")
        self.verticalLayout_5.addWidget(self.cb_builtinPlayer)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Lmedia_player = QtGui.QLabel(self.t_preferences)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lmedia_player.sizePolicy().hasHeightForWidth())
        self.Lmedia_player.setSizePolicy(sizePolicy)
        self.Lmedia_player.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Lmedia_player.setFont(font)
        self.Lmedia_player.setObjectName("Lmedia_player")
        self.horizontalLayout_4.addWidget(self.Lmedia_player)
        self.ledit_player = QtGui.QLineEdit(self.t_preferences)
        self.ledit_player.setObjectName("ledit_player")
        self.horizontalLayout_4.addWidget(self.ledit_player)
        self.btn_player = QtGui.QToolButton(self.t_preferences)
        self.btn_player.setMinimumSize(QtCore.QSize(33, 0))
        self.btn_player.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_player.setStatusTip("None")
        self.btn_player.setText("...")
        self.btn_player.setObjectName("btn_player")
        self.horizontalLayout_4.addWidget(self.btn_player)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.cb_checkLinksAuto = QtGui.QCheckBox(self.t_preferences)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_checkLinksAuto.sizePolicy().hasHeightForWidth())
        self.cb_checkLinksAuto.setSizePolicy(sizePolicy)
        self.cb_checkLinksAuto.setObjectName("cb_checkLinksAuto")
        self.verticalLayout_5.addWidget(self.cb_checkLinksAuto)
        self.tabWidget.addTab(self.t_preferences, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dl_folder = QtGui.QHBoxLayout()
        self.dl_folder.setObjectName("dl_folder")
        self.Ldl_folder = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Ldl_folder.setFont(font)
        self.Ldl_folder.setObjectName("Ldl_folder")
        self.dl_folder.addWidget(self.Ldl_folder)
        self.edit_folder = QtGui.QLineEdit(self.tab_2)
        self.edit_folder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edit_folder.setReadOnly(True)
        self.edit_folder.setObjectName("edit_folder")
        self.dl_folder.addWidget(self.edit_folder)
        self.button_folder = QtGui.QToolButton(self.tab_2)
        self.button_folder.setMinimumSize(QtCore.QSize(33, 0))
        self.button_folder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_folder.setStatusTip("None")
        self.button_folder.setText("...")
        self.button_folder.setObjectName("button_folder")
        self.dl_folder.addWidget(self.button_folder)
        self.verticalLayout.addLayout(self.dl_folder)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_afterDl = QtGui.QLabel(self.tab_2)
        self.label_afterDl.setObjectName("label_afterDl")
        self.horizontalLayout.addWidget(self.label_afterDl)
        self.combo_options = QtGui.QComboBox(self.tab_2)
        self.combo_options.setObjectName("combo_options")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.horizontalLayout.addWidget(self.combo_options)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_dc = QtGui.QLabel(self.tab_2)
        self.label_dc.setObjectName("label_dc")
        self.horizontalLayout_2.addWidget(self.label_dc)
        self.combo_dc = QtGui.QComboBox(self.tab_2)
        self.combo_dc.setObjectName("combo_dc")
        self.combo_dc.addItem("")
        self.combo_dc.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_dc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_applyToAll = QtGui.QCheckBox(self.tab)
        self.cb_applyToAll.setEnabled(True)
        self.cb_applyToAll.setObjectName("cb_applyToAll")
        self.verticalLayout_3.addWidget(self.cb_applyToAll)
        self.tree_quality = QtGui.QTreeWidget(self.tab)
        self.tree_quality.setStatusTip("")
        self.tree_quality.setObjectName("tree_quality")
        self.tree_quality.header().setDefaultSectionSize(350)
        self.tree_quality.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tree_quality)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_all_ask = QtGui.QRadioButton(self.tab)
        self.rb_all_ask.setObjectName("rb_all_ask")
        self.horizontalLayout_3.addWidget(self.rb_all_ask)
        self.rb_all_low_quality = QtGui.QRadioButton(self.tab)
        self.rb_all_low_quality.setObjectName("rb_all_low_quality")
        self.horizontalLayout_3.addWidget(self.rb_all_low_quality)
        self.rb_all_high_quality = QtGui.QRadioButton(self.tab)
        self.rb_all_high_quality.setObjectName("rb_all_high_quality")
        self.horizontalLayout_3.addWidget(self.rb_all_high_quality)
        self.rb_mixed_quality = QtGui.QRadioButton(self.tab)
        self.rb_mixed_quality.setCheckable(False)
        self.rb_mixed_quality.setObjectName("rb_mixed_quality")
        self.horizontalLayout_3.addWidget(self.rb_mixed_quality)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.t_notifications = QtGui.QWidget()
        self.t_notifications.setObjectName("t_notifications")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.t_notifications)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.g_notification = QtGui.QGroupBox(self.t_notifications)
        self.g_notification.setObjectName("g_notification")
        self.s_notifyDone = QtGui.QCheckBox(self.g_notification)
        self.s_notifyDone.setGeometry(QtCore.QRect(20, 50, 455, 23))
        self.s_notifyDone.setChecked(True)
        self.s_notifyDone.setObjectName("s_notifyDone")
        self.label_description = QtGui.QLabel(self.g_notification)
        self.label_description.setGeometry(QtCore.QRect(10, 30, 455, 23))
        self.label_description.setObjectName("label_description")
        self.s_notifyError = QtGui.QCheckBox(self.g_notification)
        self.s_notifyError.setEnabled(True)
        self.s_notifyError.setGeometry(QtCore.QRect(20, 70, 455, 23))
        self.s_notifyError.setChecked(True)
        self.s_notifyError.setObjectName("s_notifyError")
        self.f_note = QtGui.QFrame(self.g_notification)
        self.f_note.setGeometry(QtCore.QRect(10, 100, 521, 91))
        self.f_note.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_note.setFrameShadow(QtGui.QFrame.Raised)
        self.f_note.setObjectName("f_note")
        self.label_note = QtGui.QLabel(self.f_note)
        self.label_note.setGeometry(QtCore.QRect(20, 20, 511, 71))
        self.label_note.setWordWrap(True)
        self.label_note.setObjectName("label_note")
        self.label_note_info = QtGui.QLabel(self.f_note)
        self.label_note_info.setGeometry(QtCore.QRect(10, 0, 55, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_note_info.setFont(font)
        self.label_note_info.setObjectName("label_note_info")
        self.verticalLayout_4.addWidget(self.g_notification)
        self.tabWidget.addTab(self.t_notifications, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(PreferencesWindow)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.cb_applyToAll, QtCore.SIGNAL("toggled(bool)"), self.tree_quality.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(PreferencesWindow)

    def retranslateUi(self, PreferencesWindow):
        PreferencesWindow.setWindowTitle(QtGui.QApplication.translate("PreferencesWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_builtinPlayer.setText(QtGui.QApplication.translate("PreferencesWindow", "Use built-in player.", None, QtGui.QApplication.UnicodeUTF8))
        self.Lmedia_player.setText(QtGui.QApplication.translate("PreferencesWindow", "Default media player:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_checkLinksAuto.setText(QtGui.QApplication.translate("PreferencesWindow", "Automatically check for links in clipboard.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t_preferences), QtGui.QApplication.translate("PreferencesWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.Ldl_folder.setText(QtGui.QApplication.translate("PreferencesWindow", "Default download folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_afterDl.setText(QtGui.QApplication.translate("PreferencesWindow", "Default action after download:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(0, QtGui.QApplication.translate("PreferencesWindow", "Do Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(1, QtGui.QApplication.translate("PreferencesWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(2, QtGui.QApplication.translate("PreferencesWindow", "Convert to Ogg/Vorbis (Audio)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(3, QtGui.QApplication.translate("PreferencesWindow", "Convert to Ogg/Theora (Video)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_options.setItemText(4, QtGui.QApplication.translate("PreferencesWindow", "Rip Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dc.setText(QtGui.QApplication.translate("PreferencesWindow", "When double-clicking a completed download:", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_dc.setItemText(0, QtGui.QApplication.translate("PreferencesWindow", "Play Local File", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_dc.setItemText(1, QtGui.QApplication.translate("PreferencesWindow", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PreferencesWindow", "Download Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_applyToAll.setText(QtGui.QApplication.translate("PreferencesWindow", "Apply to all websites (ignore list below).", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_quality.setToolTip(QtGui.QApplication.translate("PreferencesWindow", "This list contains the websites that you already accessed through WatchVideo.", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_quality.headerItem().setText(0, QtGui.QApplication.translate("PreferencesWindow", "Website", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_quality.headerItem().setText(1, QtGui.QApplication.translate("PreferencesWindow", "Video Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_all_ask.setText(QtGui.QApplication.translate("PreferencesWindow", "All Ask", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_all_low_quality.setText(QtGui.QApplication.translate("PreferencesWindow", "All Low", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_all_high_quality.setText(QtGui.QApplication.translate("PreferencesWindow", "All High", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_mixed_quality.setText(QtGui.QApplication.translate("PreferencesWindow", "Mixed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PreferencesWindow", "Video Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.g_notification.setTitle(QtGui.QApplication.translate("PreferencesWindow", "Notification Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.s_notifyDone.setText(QtGui.QApplication.translate("PreferencesWindow", "The download ends successfully.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_description.setText(QtGui.QApplication.translate("PreferencesWindow", "Show a notification message when:", None, QtGui.QApplication.UnicodeUTF8))
        self.s_notifyError.setText(QtGui.QApplication.translate("PreferencesWindow", "An error occurs.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_note.setText(QtGui.QApplication.translate("PreferencesWindow", "If you want to use your system\'s default way to popup messages you can install \'python-notify\'. \n"
"In case python-notify isn\'t installed, WatchVideo uses baloon tooltips on the tray icon provided by Qt4.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_note_info.setText(QtGui.QApplication.translate("PreferencesWindow", "Note:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.t_notifications), QtGui.QApplication.translate("PreferencesWindow", "Notifications", None, QtGui.QApplication.UnicodeUTF8))

from watchvideo import icons_rc
assert icons_rc
